server:
  port: 8080

spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.rental.payment: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

cashfree:
  app-id: ${CASHFREE_APP_ID}
  secret-key: ${CASHFREE_SECRET_KEY}
  base-url: ${CASHFREE_BASE_URL}
  webhook-secret: ${CASHFREE_WEBHOOK_SECRET}
